### ISSUE TITLE
im0 404 (Not Found)

### ISSUE THREAD

**Issue by unosbaghaie** [avatsaev/angular-cornerstone-example#1]
Hi
When I run the project, the below errors are in there 

```
zone.js:3243 GET http://localhost:4200/assets/dicom/im0 404 (Not Found)
.
.
.
zone.js:3243 GET http://localhost:4200/assets/dicom/im18 404 (Not Found)
```

**Comment by avatsaev** [comment]
You need to add those files by yourself in src assets folder

**Comment by unosbaghaie** [comment]
can you provide some sample files, because I don't have sample files?

**Comment by avatsaev** [comment]
did you get banned on google?

**Comment by Rishital** [comment]
Can you please some sample files?
Is that normal image or is it dicom file?

**Comment by avatsaev** [comment]
you need a dicom file
